## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: "Bug Report"
description: "File a bug report"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.
  - type: dropdown
    id: machine
    attributes:
      label: machine
      description: Which machine are you using?
      options:
      - Levante
      - Lumi
      - Lumi operational
      - MN5
      - MN5 operational
      - CI
      - HPC2020
      - Others
    validations:
      required: true
  - type: dropdown
    id: catalog
    attributes:
      label: catalog
      description: Which catalog are you using?
      options:
      - ci
      - climatedt-phase1
      - leonardo
      - levante
      - lumi-phase1
      - lumi-phase2
      - mn5-phase2
      - nextgems3
      - nextgems4
      - obs
      - Others (specify)
    validations:
      required: true
  - type: dropdown
    id: version-core
    attributes:
      label: version
      description: Which AQUA version are you using?
      options:
      - v0.22.0
      - v0.21.0
      - main
      - older -> not compatible with AQUA-diagnostic repository
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: version
      description: Which AQUA-diagnostic version are you using?
      options:
      - main
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what happened.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code to reproduce the issue
      description: Please copy and paste any relevant code. This will be automatically formatted into code, so no need for backticks.
      render: python
  - type: textarea
    id: error
    attributes:
      label: Error messages
      description: Please copy and paste any error messages you received.
  - type: dropdown
    id: contributor
    attributes:
      label: Are you interested in making a pull request?
      description: We welcome pull requests. As an open source project, we have limited resources and a suggested fix is very helpful.
      options:
        - 'Yes'
        - 'Maybe'
        - 'No'
    validations:
      required: false
