## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: Feature request
description: "Ask for a new feature"
labels: ["improvement", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below with details about your feature request.
  - type: textarea
    id: feature-request
    attributes:
      label: Feature request
    validations:
      required: true
