# Default date for jinja templates for reference datasets:

# default: default date range for all analyses
# radiation: date range for radiation analyses
# timeseries: date range for timeseries analyses

# startdate, enddate: values for the date range for references to be used in the analysis
# std_startdate, std_enddate: standard deviation for references to be used in the analysis

default:
  default:
    startdate: "1990-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  radiation:
    startdate: "2001-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  timeseries:
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
scenario:
  default:
    startdate: "1990-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  radiation:
    startdate: "2001-01-01"
    enddate: "2014-12-31"
    std_startdate: "1990-01-01"
    std_enddate: "2014-12-31"
  timeseries:
    std_startdate: "2020-01-01"
    std_enddate: "2024-12-31"
storyline:
  default:
    startdate: "2017-01-01"
    enddate: "2024-12-31"
    std_startdate: "2000-01-01"
    std_enddate: "2024-12-31"
  radiation:
    startdate: "2001-01-01"
    enddate: "2014-12-31"
    std_startdate: "2000-01-01"
    std_enddate: "2024-12-31"
  timeseries:
    std_startdate: "2020-01-01"
    std_enddate: "2024-12-31"
