#!/bin/bash

#SBATCH -A project_465000454
#SBATCH --nodes=1
#SBATCH --mem=512G  # Specify the memory allocation, e.g., 8 gigabytes
#SBATCH -t 0-04:00:00 #change the wallclock
#SBATCH -J aqua-TCs
#SBATCH --output=/users/pghinass/AQUA/diagnostics/tropical_cyclones/slurm_jobs/TC_slurm_%j.out
#SBATCH --error=/users/pghinass/AQUA/diagnostics/tropical_cyclones/slurm_jobs/TC_slurm_%j.err
#SBATCH -p small    #change the partition

set -e
# directory of python script to execute
DIR=/users/pghinass/AQUA/diagnostics/tropical_cyclones/cli
python $DIR/tropical_cyclones_cli.py
