from .diagnostics import get_install_paths, DIAGNOSTIC_CONFIG_DIRECTORIS, DIAGNOSTIC_TEMPLATE_DIRECTORIES

__all__ = ["get_install_paths", "DIAGNOSTIC_CONFIG_DIRECTORIS", "DIAGNOSTIC_TEMPLATE_DIRECTORIES"]