# experiment
datasets:
  - catalog: "climatedt-o25.1"
    model: "IFS-FESOM"
    exp: "historical-1990"
    source: "hourly-hpz10-atm2d"
    source2d: "hourly-hpz10-atm2d"
    source3d: "hourly-hpz10-atm3d"
    engine: "fdb"
    #reader_kwargs: {chunks: {"time": 1, "level": 1}}
    reader_kwargs: {chunks: {"time": '6h', "level": 1}}

# folders for regridded data, temprorary and stored high res data
output:
  outputdir: "/users/silvcapr/tc_analysis/"
paths:
  tmpdir: "/users/silvcapr/tc_analysis/tmpdir"
  fulldir: "/users/silvcapr/tc_analysis/fulldir"
  plotdir: "/users/silvcapr/tc_analysis/figures"
  trackdir: "/users/silvcapr/tc_analysis/trackdir"

# log level
setup:
  loglevel: 'WARNING'

# grid on which operate
grids:
  lowgrid: 'r100'
  highgrid: 'r025'

# variables to stored
varlist: ['msl', '10u', '10v', 'tprate']

# temporal definition (date format: YYYYMMDD)
time:
  startdate: '19900101'
  enddate: '20141231'
  frequency: '6h'

stream:
  streamstep: "1D" # n of days for streaming (check reader args options, IMPORTANT: must be specified in days, "D")

# detect nodes options
detect:
  boxdim: 10    # dimension of lat/lon box to save data in the vicinity of the TCs centres (in degrees)
  write_fullres: false  # Option to write zoom-in full resolution data

# stich nodes options
stitch:
  n_days_freq: 30 # run stitch nodes (tracks computation) and save tracks every n days
  n_days_ext: 2  # n of days to extend time boundaries not to miss tracks which may start/end before/after the chosen n of days

# path to orography in case file (in case var is not found in the catalog)
orography:
  file_path: null #"/work/users/mccorda/data/orog_ERA5.nc"  # path to orography file, if not null, it will override the catalog
  source_oro: "daily-hpz10-atm2d"
  var_oro: "orog"
